#!/bin/bash
#
# colorful - simple 2D sideview shooter
# Copyright (C) 2022 suve (a.k.a. Artur Frenszek-Iwicki)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu -o pipefail

function show_help() {
	cat <<EOF
configure.sh for colorful
Accepted options:

--fpc FULL_PATH
  Use the Free Pascal Compiler located at FULL_PATH.
  The default is to use "fpc".

--flags FLAGS
  Pass FLAGS to fpc. Can be specified multiple times.
  Overrides any defaults.

--ogg-quality QUALITY
  Encode sound effects to .ogg with this quality setting.
EOF
}

# Set defaults
FPC="fpc"
FPC_FLAGS="-O1 -gl -gw"
OGG_QUALITY="10"

while [[ "${#}" -gt 0 ]]; do
	if [[ "${1}" == "--help" ]]; then
		show_help
		exit
	fi

	if [[ "${1}" == "--fpc" ]]; then
		FPC="${2}"
	elif [[ "${1}" == "--flags" ]]; then
		FPC_FLAGS="${FPC_FLAGS} ${2}"
	elif [[ "${1}" == "--ogg-quality" ]]; then
		OGG_QUALITY="${2}"
	else
		echo "Unknown option \"${1}\"" >&2
		exit 1
	fi

	shift 2
done

# Print out used values

cat <<EOF
Config values:
  FPC = ${FPC}
  FPC_FLAGS = ${FPC_FLAGS}
  OGG_QUALITY = ${OGG_QUALITY}
Generating Makefile...
EOF

# cd to this script's directory and create the Makefile
cd "$(dirname "${0}")"

(cat <<EOF
# !
# ! This file has been generated by "configure.sh".
# ! Do not edit manually.
# !
FPC = ${FPC}
FPC_FLAGS = ${FPC_FLAGS}
OGG_QUALITY = ${OGG_QUALITY}
EOF
) | cat - Makefile.in > Makefile

# Print success message

echo 'Done.'
