.\" Manpage for colorful
.\" Contact veg@svgames.pl to correct errors or typos.
.TH COLORFUL 6 "2022-12-16" "2.0" "Spielanleitung"
.SH NAME
colorful - Einfacher 2D-Seitenansicht Shooter
.SH ZUSAMMENFASSUNG
\fBcolorful\fR
.SH BESCHREIBUNG
Colorful ist ein einfacher 2D Shooter, indem der Protagonist
durch ein Labyrinth aus Höhlen und Korridoren reist und dabei farbige Artifakte einsammlet. 
.SH STEUERUNG
Das Spiel wird nur mit der Tastatur gespielt. Standard Steuerung:
.TP
\fBPfeiltasten\fR
Bewegen
.TP
\fBZ\fR/\fBX\fR
Links / Rechts schießen
.TP
\fB\-\fR/\fB+\fR
Lautstärke erhöhen / Verringern
.TP
\fBP\fR
Spiel pausieren
.TP
Die Tastaturbelegung ist frei anpassbar.
.SH VERZEICHNISSE
Die Spieldateien befinden sich unter: \fB/usr/share/suve/colorful\fR. 
Das Spiel speicher seine Einstellungen und die Spielstände unter: \fB~/.local/share/suve/colorful/\fR.
