.\" דף הוראות של Colorful
.\" צרו קשר עם veg@svgames.pl לתיקוני בעיות או שגיאות.
.TH COLORFUL 6 "2022-12-16" "2.0" "מדריך המשחק"
.SH שם
colorful - משחק יריות פשוט בדו-מימד.
.SH תיאור
\fBcolorful\fR
.SH תיאור
Colorful הוא משחק פשוט יריות פשוט דו-מימדי, בו הפרוטגוניסט מטייל במבוך של 
מערות ומסדרונות במטרה לאסוף יצירות צבע.
.SH דרכי קלט
המשחק משוחק בעזרת המקלדת בלבד. הגדרות החצים במתכונת ברירת מחדל:
.TP
\fBמקשי החצים\fR
תנועה
.TP
\fBZ\fR/\fBX\fR
ירייה שמאלה או ימינה
.TP
\fB\-\fR/\fB+\fR
הגברת או הנמכת הקול
.TP
\fBP\fR
השהייה או החזרה של המשחק
.TP
ניתן לשנות את כל הגדרות המקשים הללו.
.SH תיקיות
קבצי נתוני המשחק שמורים ב- \fB/usr/share/suve/colorful\fR. 
המשחק מאחסן את ההגדרות והמשחקים השמורים ב- \fB~/.local/share/suve/colorful/\fR.
