.\" Manpage for colorful
.\" Contact veg@svgames.pl to correct errors or typos.
.TH COLORFUL 6 "2022-12-16" "2.0" "Manual Permainan"
.SH NAMA
colorful - Tembak-tembakan 2D sederhana
.SH SINOPSIS
\fBcolorful\fR
.SH DESKRIPSI
Colorful adalah permainan tembak-tembakan sederhana dari samping, dimana protagonis
perjalanan labirin gua dan koridor untuk mendapatkan artifak warna.
.SH KONTROL
Permainan ini dimainkan menggunakan papan tik. Tombol default:
.TP
\fBTombol Arah\fR
Pergerakan
.TP
\fBZ\fR/\fBX\fR
Tembak kiri /kanan
.TP
\fB\-\fR/\fB+\fR
Volume turun / naik
.TP
\fBP\fR
Tunda / mulai
.TP
Tombol ini bisa diatur ulang seluruhnya.
.SH DIREKTORI
Berkas permainan berlokasi di \fB/usr/share/suve/colorful\fR. 
Permainan ini menyimpan pengaturan dan savegames di \fB~/.local/share/suve/colorful/\fR.
