.\" Manpage para colorful
.\" Entre em contato com veg@svgames.pl para corrigir erros de digitação.
.TH COLORFUL 6 "2022-12-16" "2.0" "Manual do Jogo"
.SH NOME
colorful - um simples jogo de tiro 2D
.SH SINOPSE
\fBcolorful\fR
.SH DESCRIÇÃO
Colorful é um jogo de tiro simples em visão lateral, onde o protagonista 
viaja num labirinto de cavernas e corredores para coletar objetos coloridos.
.SH CONTROLES
O único controle para o jogo é o teclado. Os controles são:
.TP
\fBTeclas direcionais (setas)\fR
Movimentar
.TP
\fBZ\fR/\fBX\fR
Tiro esquerda / direita
.TP
\fB\-\fR/\fB+\fR
Volume baixo / alto
.TP
\fBP\fR
Pausa / tira a pausa
.TP
Essas teclas podem ser redefinidas.
.SH DIRETÓRIOS
Os arquivos de dados ficam em \fB/usr/share/suve/colorful\fR. 
O armazenamento de configurações e savegames em \fB~/.local/share/suve/colorful/\fR.
