.\" Manpage for colorful
.\" Contact veg@svgames.pl to correct errors or typos.
.TH COLORFUL 6 "2022-12-16" "2.0" "Manualul Jocului"
.SH NUME
colorful - joc shooter simplu 2D sideview
.SH REZUMAT
\fBcolorful\fR
.SH DESCRIERE
Colorful este un simplu joc shooter sideview, în care protagonistul străbate 
un labirint de peșteri și coridoare pentru a strânge artefacte colour.
.SH CONTROALE
Jocul este jucat folosind doar tastatura. Scurtăturile implicite:
.TP
\fBSăgeți direcționale\fR
Mișcare
.TP
\fBZ\fR/\fBX\fR
Trage stânga / dreapta
.TP
\fB\-\fR/\fB+\fR
Volum sus / jos
.TP
\fBP\fR
Pauză / anulați pauza
.TP
Scurtăturile implicite pot fi redefinite complet.
.SH LOCAȚII
Fișierele cu datele jocului sunt localizate în \fB/usr/share/suve/colorful\fR.
Jocul are setările și salvările în \fB~/.local/share/suve/colorful/\fR.
