.\" Manpage for colorful
.\" Contact veg@svgames.pl to correct errors or typos.
.TH COLORFUL 6 "2022-12-16" "2.0" "Руководство по игре"
.SH НАЗВАНИЕ
colorful - простой 2D шутер
.SH ОБЗОР
\fBcolorful\fR
.SH ОПИСАНИЕ
Colorful это простая игра-шутер с видом сбоку, где главный герой
путешествует в лабиринте из пещер и коридоров, собирая цветные артефакты.
.SH УПРАВЛЕНИЕ
Управление игрой доступно только с клавиатуры. Стандартные назначения клавиш:
.TP
\fBКлавиши со стрелками\fR
Передвижение
.TP
\fBZ\fR/\fBX\fR
Выстрелить влево / вправо
.TP
\fB\-\fR/\fB+\fR
Уменьшить / увеличить громкость
.TP
\fBP\fR
Пауза
.TP
Назначения клавиш можно изменить по желанию.
.SH ФАЙЛЫ
Файлы игры расположены в папке \fB/usr/share/suve/colorful\fR. 
Игра хранит свои настройки и сохранения в папке \fB~/.local/share/suve/colorful/\fR.
