.\" Manpage for colorful
.\" Contact veg@svgames.pl to correct errors or typos.
.TH COLORFUL 6 "2022-12-16" "2.0" "Інструкція"
.SH НАЗВА
colorful - проста 2D-стрілялка
.SH СИНОПСИС
\fBcolorful\fR
.SH ОПИС
Colorful - це простий шутер із виглядом "з боку", де протагоніст подорожує
лабіринтом із печер і коридорів з метою зібрати кольорові артефакти.
.SH КЕРУВАННЯ
Керування грою - виключно клавіатурою. За замовчуванням клавіші наступні:
.TP
\fBКлавіші зі стрілками\fR
Переміщення
.TP
\fBZ\fR/\fBX\fR
Стріляти ліворуч / праворуч
.TP
\fB\-\fR/\fB+\fR
Зменшити / збільшити гучність
.TP
\fBP\fR
Пауза / зняти паузу
.TP
Ці клавіші можна змінити.
.SH ДАНІ
Гра зберігає свої файли із даними у \fB/usr/share/suve/colorful\fR.
А налаштування і збережені ігри знаходяться у \fB~/.local/share/suve/colorful/\fR.
